### ISSUE TITLE
The file /etc/group is missing on some Cygwin installations

### ISSUE THREAD

**Issue by mosbth** [mosbth/dbwebb-cli#32]
Recheck the code if this is needed. In the config-file a check is done towards this file. Remove, change or otherwise deal with that check.

**Comment by it17261** [comment]
I've the same problem. After installing latest Cygwin 2.870 (32 bit) the /etc/group file isn't present. I can manually create, but some files that need to have "root" group were created with "Administrators" group.

**Comment by mosbth** [comment]
The new version of dbwebb does not use /etc/group so its not a problem anymore.
