### ISSUE TITLE
ZSH compatible 

### ISSUE THREAD

**Issue by foikila** [mosbth/dbwebb-cli#50]
Make dbwebb-cli comatible with zsh.

**Comment by mosbth** [comment]
Its possible to execute dbwebb within a zsh. What is the error?

**Comment by foikila** [comment]
It  was the installation of dbwebb that failed with zsh... 

$ install dbwebb /usr/local/bin/dbwebb
$ E: Unable to locate package dbwebb                                                                                                                                              $ E: Unable to locate package /usr/local/bin

**Comment by foikila** [comment]
Found the problem... I have install as an alias....
