### ISSUE TITLE
Failed to upload course fodler to www/, htmlphp-v2

### ISSUE THREAD

**Issue by lewenhagen** [mosbth/dbwebb-cli#51]
1. When executing "dbwebb init", no folder is created in www/: http://puu.sh/j19jK/bfd07dcf95.png
2. Can not execute "dbwebb publish kmom01": http://puu.sh/iZSYQ/3e9f7d900e.png
3. The pointer, "dbwebb-validate --help", does not work either

**Comment by mosbth** [comment]
Ok. Will check the init process and update how directories are created.

```
desktop:~/dbwebb-kurser/htmlphp/me/kmom04/lab3$ dbwebb publish kmom02
Uploading the directory '/home/mos/dbwebb-kurser/htmlphp/me/kmom02/' to 'mosstud@ssh.student.bth.se:dbwebb-kurser/htmlp
hp/me/kmom02/' to validate and publish.
Press enter to continue...
sending incremental file list

sent 216 bytes  received 16 bytes  154.67 bytes/sec
total size is 26,064  speedup is 112.34
FAILED --publish-to 'www/dbwebb-kurser/htmlphp/me/kmom02' is not a valid directory.
```

**Comment by mosbth** [comment]
A workaround is to do `dbwebb publish` first, to create the directory structure. Then individual parts can be published.
