### ISSUE TITLE
Provide a more verbose warning if selfupdate fails

### ISSUE THREAD

**Issue by mosbth** [mosbth/dbwebb-cli#70]
For example due to missing sudo.

**Comment by pejg12** [comment]
Såhär ser output ut just nu:
```
$ dbwebb selfupdate
Your current version is: dbwebb version v1.9.34 (2016-02-05)
Selfupdating 'dbwebb' from https://raw.githubusercontent.com/mosbth/dbwebb-cli
Downloading... installing...install: cannot remove ‘/usr/local/bin/dbwebb’: Permission denied
cleaning up... done.
DONE to update 'dbwebb'.
The updated version is now: dbwebb version v1.9.34 (2016-02-05)
DONE The config file '/home/allinrep/.dbwebb.config' is now up-to-date.
```

Felmeddelandet: `install: cannot remove ‘/usr/local/bin/dbwebb’: Permission denied`

Felet kan spåras till [dbwebb2-functions.bash rad 519](https://github.com/mosbth/dbwebb-cli/blob/master/dbwebb2-functions.bash#L519) och handlar om att `install /tmp/$$ $target;` felar men resten av raden fortsätter ändå.

Lösningen på problemet kan vara en felhantering likt den i [install.bash](https://github.com/mosbth/dbwebb-cli/blob/master/install.bash) där varje kommando körs separat med rimliga if-satser.
