### ISSUE TITLE
Students sometimes name .png files wrong

### ISSUE THREAD

**Issue by foikila** [mosbth/dbwebb-cli#76]
Students sometimes name .png files wrong and instead name them .PNG. This causes dbwebb inspect to fail even though they have the correct file there but hade the wrong fileextenstion.

It would be nice if dbwebb checks for both extendtions instead of just failing. 

This occur in cource Linux kmom01 with the file SSH.png

**Comment by pejg12** [comment]
Would be nice if it was consistently case insensitive when looking for files, since many students use Windows as their main environment.

**Comment by mosbth** [comment]
Enhanced the labspec to make the student aware on this and encouraged students to run dbwebb inspect by themselves.

Thats the way to work around this.
